title: Internet-of-Things Excursions with Micro Python
description: A Hands on approach to learning IoT
theme: just-the-docs

url: https://salirzaidi.github.io/comms/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
